# Generated by Django 5.2.17 on 2026-10-02 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_product_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgechunk',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.productdocument'),
        ),
        migrations.AddField(
            model_name='productdocument',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
