# Generated by Django 5.2.17 on 2026-10-02 05:27

from django.db import migrations, models



DOCUMENT_MARKER = " / 문서: "


def link_legacy_document_chunks(apps, schema_editor):
    """Chunks indexed before KnowledgeChunk.document existed have document=NULL even when
    they came from an uploaded file. Link them by header ("... / 문서: <label>") so that
    re-embedding only the product fields never deletes document content."""
    KnowledgeChunk = apps.get_model("knowledge", "KnowledgeChunk")
    ProductDocument = apps.get_model("knowledge", "ProductDocument")
    for chunk in KnowledgeChunk.objects.filter(
        source_type="product", document__isnull=True, content__contains=DOCUMENT_MARKER
    ):
        header = chunk.content.split("\n", 1)[0]
        if DOCUMENT_MARKER not in header:
            continue
        label = header.split(DOCUMENT_MARKER, 1)[1]
        for document in ProductDocument.objects.filter(product_id=chunk.source_id):
            labels = {document.file_name}
            if document.title:
                labels.add(f"{document.title} ({document.file_name})")
            if label in labels:
                chunk.document_id = document.pk
                chunk.save(update_fields=["document"])
                break

class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_document_titles'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='knowledgechunk',
            name='uniq_chunk_per_source',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='uniq_product_name_per_company',
        ),
        migrations.RunPython(link_legacy_document_chunks, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_id', 'document', 'chunk_index'), name='uniq_chunk_per_section', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'name', 'category'), name='uniq_product_name_category_per_company'),
        ),
    ]
