# Generated by Django 5.2.17 on 2026-10-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anthropic_api_key_encrypted', models.TextField(blank=True, default='')),
                ('api_key_last4', models.CharField(blank=True, default='', max_length=4)),
                ('api_key_updated_at', models.DateTimeField(blank=True, null=True)),
                ('claude_model', models.CharField(default='claude-opus-5-5', max_length=100)),
                ('bot_name', models.CharField(default='고객지원 챗봇', max_length=100)),
                ('welcome_message', models.TextField(default='안녕하세요! 회사와 제품에 대해 궁금한 점을 물어보세요.')),
                ('extra_instructions', models.TextField(blank=True, default='', max_length=2000)),
            ],
            options={
                'verbose_name': 'system setting',
            },
        ),
    ]
