# Generated by Django 5.2.17 on 2026-10-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='chunk_max_chars',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='chunk_overlap_chars',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='embedding_model',
            field=models.CharField(default='intfloat/multilingual-e5-small', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='history_messages',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='llm_max_output_tokens',
            field=models.PositiveIntegerField(default=4096),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='max_sources',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='retrieval_max_distance',
            field=models.FloatField(default=0.6),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='retrieval_top_k',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='search_with_previous_question',
            field=models.BooleanField(default=True),
        ),
    ]
