# Generated by Django 5.2.17 on 2026-10-02 03:28

from django.db import migrations, models



def copy_claude_settings(apps, schema_editor):
    """Move the Claude key/model from SystemSetting into LLMProviderConfig('anthropic')."""
    SystemSetting = apps.get_model("settings_app", "SystemSetting")
    Config = apps.get_model("settings_app", "LLMProviderConfig")
    for setting in SystemSetting.objects.all():
        has_key = bool(setting.anthropic_api_key_encrypted)
        Config.objects.update_or_create(
            provider="anthropic",
            defaults={
                "api_key_encrypted": setting.anthropic_api_key_encrypted,
                "api_key_hint": f"sk-ant-...{setting.api_key_last4}" if has_key else "",
                "api_key_updated_at": setting.api_key_updated_at,
                "model": setting.claude_model or "claude-opus-5-5",
            },
        )


def copy_back(apps, schema_editor):
    SystemSetting = apps.get_model("settings_app", "SystemSetting")
    Config = apps.get_model("settings_app", "LLMProviderConfig")
    config = Config.objects.filter(provider="anthropic").first()
    if config is None:
        return
    for setting in SystemSetting.objects.all():
        setting.anthropic_api_key_encrypted = config.api_key_encrypted
        setting.api_key_last4 = config.api_key_hint[-4:] if config.api_key_encrypted else ""
        setting.api_key_updated_at = config.api_key_updated_at
        setting.claude_model = config.model or "claude-opus-5-5"
        setting.save()

class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_rag_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('anthropic', 'Claude'), ('openai', 'ChatGPT'), ('gemini', 'Gemini')], max_length=20, unique=True)),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('api_key_hint', models.CharField(blank=True, default='', max_length=32)),
                ('api_key_updated_at', models.DateTimeField(blank=True, null=True)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='llm_provider',
            field=models.CharField(choices=[('anthropic', 'Claude'), ('openai', 'ChatGPT'), ('gemini', 'Gemini')], default='anthropic', max_length=20),
        ),
        migrations.RunPython(copy_claude_settings, copy_back),
        migrations.RemoveField(
            model_name='systemsetting',
            name='anthropic_api_key_encrypted',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='api_key_last4',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='api_key_updated_at',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='claude_model',
        ),
    ]
