# Generated by Django 5.2.17 on 2026-10-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_llm_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmproviderconfig',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
