# Generated by Django 5.2.17 on 2026-10-02 05:50

import chat.prompts
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_provider_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='system_prompt',
            field=models.TextField(default=chat.prompts.default_system_prompt, max_length=10000),
        ),
    ]
